-- MySQL Script generated by MySQL Workbench
-- Mon Mar 13 11:16:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`articulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`articulo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`articulo` (
  `idarticulo` INT NOT NULL,
  `codigo` VARCHAR(50) NULL,
  `nombre` VARCHAR(45) NULL,
  `stock` INT NULL,
  `descripcion` VARCHAR(255) NULL,
  `imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`idarticulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articulo_has_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`articulo_has_venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`articulo_has_venta` (
  `idventa` INT UNSIGNED NOT NULL,
  `articulo_idarticulo` INT NOT NULL,
  `venta_idventa` INT NOT NULL,
  `nombre_articulo` VARCHAR(45) NULL,
  `codigo` VARCHAR(50) NULL,
  PRIMARY KEY (`idventa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `articulo_idarticulo` INT NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`detalle_venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`detalle_venta` (
  `iddetalle_venta` INT NOT NULL,
  `cantidad` INT NULL,
  `precio` DECIMAL(11,2) NULL,
  `documento` DECIMAL(11,2) NULL,
  `venta_idventa` INT NOT NULL,
  PRIMARY KEY (`iddetalle_venta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `telefono` VARCHAR(20) NULL,
  `direccion` VARCHAR(70) NULL,
  `email` VARCHAR(50) NULL,
  `tipo_documento` VARCHAR(20) NULL,
  `num_documento` VARCHAR(20) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venta` (
  `idventa` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NULL,
  `num_comprobante` VARCHAR(10) NULL,
  `fecha` DATETIME NULL,
  `total` DECIMAL(11,2) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idventa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
